export const $$registerFieldClass = Symbol('$$registerFieldClass');
export const $$fieldClasses = Symbol('$$fieldClasses');
export const $$owner        = Symbol('$$owner');
export const $$key          = Symbol('$$key');
export const $$desc         = Symbol('$$key');
export const $$value        = Symbol('$$value');
// export const $$pristine     = Symbol('$$pristine');// TODO: remove all 'pristine' related stuff from the field classes
export const $$initSet      = Symbol('$$initSet');
export const $$entriesIn    = Symbol('$$entriesIn');
export const $$initialized  = Symbol('$$initialized');
export const $$destruct     = Symbol('$$destruct');
